services:

  joomla:
    build:
      context: .
      args:
        WWWUSER: ${WWWUSER}
        WWWGROUP: ${WWWGROUP}
    #image: ${JOOMLA_IMAGE}
    restart: always
    ports:
      - "8080:80"
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_USER: ${DB_USER}
      JOOMLA_DB_PASSWORD: ${DB_PASSWORD}
      JOOMLA_DB_NAME: ${DB_NAME}
      JOOMLA_SITE_NAME: Joomla
      JOOMLA_ADMIN_USER: Joomla Hero
      JOOMLA_ADMIN_USERNAME: joomla
      JOOMLA_ADMIN_PASSWORD: joomla@secured
      JOOMLA_ADMIN_EMAIL: joomla@example.com
    volumes:
      - ./joomla_data:/var/www/html
      - ./repos/templates/cassiopeia_joomlaboot:/var/www/html/templates/cassiopeia_joomlaboot
      - ./repos/modules/mod_joomlaboot_carousel:/var/www/html/modules/mod_joomlaboot_carousel
      - ./repos/modules/mod_joomlaboot_faq:/var/www/html/modules/mod_joomlaboot_faq
    networks:
      - joomla_network

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - joomla_network

volumes:
  joomla_data:
  db_data:

networks:
  joomla_network:
